[2023-03-22T04:39:21.261+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: CarFine.get_file scheduled__2023-03-22T04:30:00+00:00 [queued]>
[2023-03-22T04:39:21.267+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: CarFine.get_file scheduled__2023-03-22T04:30:00+00:00 [queued]>
[2023-03-22T04:39:21.267+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T04:39:21.268+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-22T04:39:21.268+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T04:39:21.277+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): get_file> on 2023-03-22 04:30:00+00:00
[2023-03-22T04:39:21.280+0000] {standard_task_runner.py:55} INFO - Started process 2383 to run task
[2023-03-22T04:39:21.282+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'CarFine', 'get_file', 'scheduled__2023-03-22T04:30:00+00:00', '--job-id', '279', '--raw', '--subdir', 'DAGS_FOLDER/CarFineDAG.py', '--cfg-path', '/tmp/tmpd4dce6cf']
[2023-03-22T04:39:21.282+0000] {standard_task_runner.py:83} INFO - Job 279: Subtask get_file
[2023-03-22T04:39:21.322+0000] {task_command.py:388} INFO - Running <TaskInstance: CarFine.get_file scheduled__2023-03-22T04:30:00+00:00 [running]> on host f331b8a34e72
[2023-03-22T04:39:21.370+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=CarFine
AIRFLOW_CTX_TASK_ID=get_file
AIRFLOW_CTX_EXECUTION_DATE=2023-03-22T04:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-22T04:30:00+00:00
[2023-03-22T04:39:21.371+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-22T04:39:21.371+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'wget -P /media https://www.dl.dropboxusercontent.com/s/q1de0kkhhxp5vo9/data.json']
[2023-03-22T04:39:21.379+0000] {subprocess.py:86} INFO - Output:
[2023-03-22T04:39:21.382+0000] {subprocess.py:93} INFO - --2023-03-22 04:39:21--  https://www.dl.dropboxusercontent.com/s/q1de0kkhhxp5vo9/data.json
[2023-03-22T04:39:21.512+0000] {subprocess.py:93} INFO - Resolving www.dl.dropboxusercontent.com (www.dl.dropboxusercontent.com)... 162.125.81.15, 2620:100:6031:15::a27d:510f
[2023-03-22T04:39:21.591+0000] {subprocess.py:93} INFO - Connecting to www.dl.dropboxusercontent.com (www.dl.dropboxusercontent.com)|162.125.81.15|:443... connected.
[2023-03-22T04:39:22.520+0000] {subprocess.py:93} INFO - HTTP request sent, awaiting response... 200 OK
[2023-03-22T04:39:22.521+0000] {subprocess.py:93} INFO - Length: 259778 (254K) [text/plain]
[2023-03-22T04:39:22.521+0000] {subprocess.py:93} INFO - /media/data.json: Permission denied
[2023-03-22T04:39:22.522+0000] {subprocess.py:93} INFO - 
[2023-03-22T04:39:22.522+0000] {subprocess.py:93} INFO - Cannot write to ‘/media/data.json’ (Permission denied).
[2023-03-22T04:39:22.523+0000] {subprocess.py:97} INFO - Command exited with return code 3
[2023-03-22T04:39:22.533+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 3.
[2023-03-22T04:39:22.535+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=CarFine, task_id=get_file, execution_date=20230322T043000, start_date=20230322T043921, end_date=20230322T043922
[2023-03-22T04:39:22.546+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 279 for task get_file (Bash command failed. The command returned a non-zero exit code 3.; 2383)
[2023-03-22T04:39:22.581+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-22T04:39:22.602+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
